AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API using SAM

Globals:
  Function:
    MemorySize: 128
    Timeout: 3
    Runtime: nodejs10.x
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
  
Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: sam-rest-api-TestPolicy
      PrimaryKey:
        Name: userid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  GetUserTestPolicy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get.handler
      # Policies: AmazonDynamoDBReadOnlyAccess  # AWS Managed Policy # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#properties
      Policies:
      - Statement:
        - Sid: dynamoDBGetItemSAMRestAPI  # inline policy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          Resource: '*'
      Events:
        GetUserApi:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: get

  PostUserTestPolicy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post.handler
      # Policies: AmazonDynamoDBFullAccess  # AWS Managed Policy
      Policies:
      - Statement:
        - Sid: dynamoDBPostItemSAMRestAPI   # inline policy
          Effect: Allow
          Action: 
          - dynamodb:PutItem
          Resource: '*'
      Events:
        PostUserApi:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: post

  DeleteUserTestPolicy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        DeleteUserApi:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: delete